/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordsRouteImport } from './routes/words'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StargazingRouteImport } from './routes/stargazing'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as MapRouteImport } from './routes/map'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as FootballRouteImport } from './routes/football'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as CuisineRouteImport } from './routes/cuisine'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as CinemaRouteImport } from './routes/cinema'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as CuratorRouteRouteImport } from './routes/curator/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FiguresIndexRouteImport } from './routes/figures.index'
import { Route as CuratorIndexRouteImport } from './routes/curator/index'
import { Route as TheaterMatchIdRouteImport } from './routes/theater.$matchId'
import { Route as RegionRegionIdRouteImport } from './routes/region.$regionId'
import { Route as QuizEraIdRouteImport } from './routes/quiz.$eraId'
import { Route as JourneysJourneyIdRouteImport } from './routes/journeys.$journeyId'
import { Route as FiguresQuizRouteImport } from './routes/figures.quiz'
import { Route as FiguresFigureIdRouteImport } from './routes/figures.$figureId'
import { Route as EraEraIdRouteImport } from './routes/era.$eraId'
import { Route as CuratorTranslationsRouteImport } from './routes/curator/translations'
import { Route as CuratorTechnicalRouteImport } from './routes/curator/technical'
import { Route as CuratorSourcesRouteImport } from './routes/curator/sources'
import { Route as CuratorSettingsRouteImport } from './routes/curator/settings'
import { Route as CuratorRoadmapRouteImport } from './routes/curator/roadmap'
import { Route as CuratorReleasesRouteImport } from './routes/curator/releases'
import { Route as CuratorQualityRouteImport } from './routes/curator/quality'
import { Route as CuratorPublishingRouteImport } from './routes/curator/publishing'
import { Route as CuratorPreservationRouteImport } from './routes/curator/preservation'
import { Route as CuratorMediaRouteImport } from './routes/curator/media'
import { Route as CuratorFootballRouteImport } from './routes/curator/football'
import { Route as CuratorEducationRouteImport } from './routes/curator/education'
import { Route as CuratorDecisionsRouteImport } from './routes/curator/decisions'
import { Route as CuratorCoverageRouteImport } from './routes/curator/coverage'
import { Route as CuratorContributorsRouteImport } from './routes/curator/contributors'
import { Route as CuratorContentRouteImport } from './routes/curator/content'
import { Route as CuratorBlueprintRouteImport } from './routes/curator/blueprint'
import { Route as CuratorAnalyticsRouteImport } from './routes/curator/analytics'
import { Route as CuratorAcquisitionsRouteImport } from './routes/curator/acquisitions'
import { Route as CultureTopicIdRouteImport } from './routes/culture.$topicId'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'
import { Route as ApiCuratorRouteImport } from './routes/api/curator'
import { Route as FiguresCollectionCollectionIdRouteImport } from './routes/figures.collection.$collectionId'

const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StargazingRoute = StargazingRouteImport.update({
  id: '/stargazing',
  path: '/stargazing',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballRoute = FootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineRoute = CuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaRoute = CinemaRouteImport.update({
  id: '/cinema',
  path: '/cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorRouteRoute = CuratorRouteRouteImport.update({
  id: '/curator',
  path: '/curator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresIndexRoute = FiguresIndexRouteImport.update({
  id: '/figures/',
  path: '/figures/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorIndexRoute = CuratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const TheaterMatchIdRoute = TheaterMatchIdRouteImport.update({
  id: '/theater/$matchId',
  path: '/theater/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRegionIdRoute = RegionRegionIdRouteImport.update({
  id: '/region/$regionId',
  path: '/region/$regionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizEraIdRoute = QuizEraIdRouteImport.update({
  id: '/quiz/$eraId',
  path: '/quiz/$eraId',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysJourneyIdRoute = JourneysJourneyIdRouteImport.update({
  id: '/journeys/$journeyId',
  path: '/journeys/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresQuizRoute = FiguresQuizRouteImport.update({
  id: '/figures/quiz',
  path: '/figures/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresFigureIdRoute = FiguresFigureIdRouteImport.update({
  id: '/figures/$figureId',
  path: '/figures/$figureId',
  getParentRoute: () => rootRouteImport,
} as any)
const EraEraIdRoute = EraEraIdRouteImport.update({
  id: '/era/$eraId',
  path: '/era/$eraId',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorTranslationsRoute = CuratorTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorTechnicalRoute = CuratorTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorSourcesRoute = CuratorSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorSettingsRoute = CuratorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorRoadmapRoute = CuratorRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorReleasesRoute = CuratorReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorQualityRoute = CuratorQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorPublishingRoute = CuratorPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorPreservationRoute = CuratorPreservationRouteImport.update({
  id: '/preservation',
  path: '/preservation',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorMediaRoute = CuratorMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorFootballRoute = CuratorFootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorEducationRoute = CuratorEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorDecisionsRoute = CuratorDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorCoverageRoute = CuratorCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorContributorsRoute = CuratorContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorContentRoute = CuratorContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorBlueprintRoute = CuratorBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorAnalyticsRoute = CuratorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CuratorAcquisitionsRoute = CuratorAcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => CuratorRouteRoute,
} as any)
const CultureTopicIdRoute = CultureTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => CultureRoute,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/$clubId',
  path: '/$clubId',
  getParentRoute: () => ClubsRoute,
} as any)
const ApiCuratorRoute = ApiCuratorRouteImport.update({
  id: '/api/curator',
  path: '/api/curator',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresCollectionCollectionIdRoute =
  FiguresCollectionCollectionIdRouteImport.update({
    id: '/figures/collection/$collectionId',
    path: '/figures/collection/$collectionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curator': typeof CuratorRouteRouteWithChildren
  '/atlas': typeof AtlasRoute
  '/chronicle': typeof ChronicleRoute
  '/cinema': typeof CinemaRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/compare': typeof CompareRoute
  '/cuisine': typeof CuisineRoute
  '/culture': typeof CultureRouteWithChildren
  '/football': typeof FootballRoute
  '/ideas': typeof IdeasRoute
  '/lessons': typeof LessonsRoute
  '/map': typeof MapRoute
  '/moments': typeof MomentsRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/stargazing': typeof StargazingRoute
  '/timeline': typeof TimelineRoute
  '/words': typeof WordsRoute
  '/api/curator': typeof ApiCuratorRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/culture/$topicId': typeof CultureTopicIdRoute
  '/curator/acquisitions': typeof CuratorAcquisitionsRoute
  '/curator/analytics': typeof CuratorAnalyticsRoute
  '/curator/blueprint': typeof CuratorBlueprintRoute
  '/curator/content': typeof CuratorContentRoute
  '/curator/contributors': typeof CuratorContributorsRoute
  '/curator/coverage': typeof CuratorCoverageRoute
  '/curator/decisions': typeof CuratorDecisionsRoute
  '/curator/education': typeof CuratorEducationRoute
  '/curator/football': typeof CuratorFootballRoute
  '/curator/media': typeof CuratorMediaRoute
  '/curator/preservation': typeof CuratorPreservationRoute
  '/curator/publishing': typeof CuratorPublishingRoute
  '/curator/quality': typeof CuratorQualityRoute
  '/curator/releases': typeof CuratorReleasesRoute
  '/curator/roadmap': typeof CuratorRoadmapRoute
  '/curator/settings': typeof CuratorSettingsRoute
  '/curator/sources': typeof CuratorSourcesRoute
  '/curator/technical': typeof CuratorTechnicalRoute
  '/curator/translations': typeof CuratorTranslationsRoute
  '/era/$eraId': typeof EraEraIdRoute
  '/figures/$figureId': typeof FiguresFigureIdRoute
  '/figures/quiz': typeof FiguresQuizRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/quiz/$eraId': typeof QuizEraIdRoute
  '/region/$regionId': typeof RegionRegionIdRoute
  '/theater/$matchId': typeof TheaterMatchIdRoute
  '/curator/': typeof CuratorIndexRoute
  '/figures/': typeof FiguresIndexRoute
  '/figures/collection/$collectionId': typeof FiguresCollectionCollectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/chronicle': typeof ChronicleRoute
  '/cinema': typeof CinemaRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/compare': typeof CompareRoute
  '/cuisine': typeof CuisineRoute
  '/culture': typeof CultureRouteWithChildren
  '/football': typeof FootballRoute
  '/ideas': typeof IdeasRoute
  '/lessons': typeof LessonsRoute
  '/map': typeof MapRoute
  '/moments': typeof MomentsRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/stargazing': typeof StargazingRoute
  '/timeline': typeof TimelineRoute
  '/words': typeof WordsRoute
  '/api/curator': typeof ApiCuratorRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/culture/$topicId': typeof CultureTopicIdRoute
  '/curator/acquisitions': typeof CuratorAcquisitionsRoute
  '/curator/analytics': typeof CuratorAnalyticsRoute
  '/curator/blueprint': typeof CuratorBlueprintRoute
  '/curator/content': typeof CuratorContentRoute
  '/curator/contributors': typeof CuratorContributorsRoute
  '/curator/coverage': typeof CuratorCoverageRoute
  '/curator/decisions': typeof CuratorDecisionsRoute
  '/curator/education': typeof CuratorEducationRoute
  '/curator/football': typeof CuratorFootballRoute
  '/curator/media': typeof CuratorMediaRoute
  '/curator/preservation': typeof CuratorPreservationRoute
  '/curator/publishing': typeof CuratorPublishingRoute
  '/curator/quality': typeof CuratorQualityRoute
  '/curator/releases': typeof CuratorReleasesRoute
  '/curator/roadmap': typeof CuratorRoadmapRoute
  '/curator/settings': typeof CuratorSettingsRoute
  '/curator/sources': typeof CuratorSourcesRoute
  '/curator/technical': typeof CuratorTechnicalRoute
  '/curator/translations': typeof CuratorTranslationsRoute
  '/era/$eraId': typeof EraEraIdRoute
  '/figures/$figureId': typeof FiguresFigureIdRoute
  '/figures/quiz': typeof FiguresQuizRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/quiz/$eraId': typeof QuizEraIdRoute
  '/region/$regionId': typeof RegionRegionIdRoute
  '/theater/$matchId': typeof TheaterMatchIdRoute
  '/curator': typeof CuratorIndexRoute
  '/figures': typeof FiguresIndexRoute
  '/figures/collection/$collectionId': typeof FiguresCollectionCollectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curator': typeof CuratorRouteRouteWithChildren
  '/atlas': typeof AtlasRoute
  '/chronicle': typeof ChronicleRoute
  '/cinema': typeof CinemaRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/compare': typeof CompareRoute
  '/cuisine': typeof CuisineRoute
  '/culture': typeof CultureRouteWithChildren
  '/football': typeof FootballRoute
  '/ideas': typeof IdeasRoute
  '/lessons': typeof LessonsRoute
  '/map': typeof MapRoute
  '/moments': typeof MomentsRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/stargazing': typeof StargazingRoute
  '/timeline': typeof TimelineRoute
  '/words': typeof WordsRoute
  '/api/curator': typeof ApiCuratorRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/culture/$topicId': typeof CultureTopicIdRoute
  '/curator/acquisitions': typeof CuratorAcquisitionsRoute
  '/curator/analytics': typeof CuratorAnalyticsRoute
  '/curator/blueprint': typeof CuratorBlueprintRoute
  '/curator/content': typeof CuratorContentRoute
  '/curator/contributors': typeof CuratorContributorsRoute
  '/curator/coverage': typeof CuratorCoverageRoute
  '/curator/decisions': typeof CuratorDecisionsRoute
  '/curator/education': typeof CuratorEducationRoute
  '/curator/football': typeof CuratorFootballRoute
  '/curator/media': typeof CuratorMediaRoute
  '/curator/preservation': typeof CuratorPreservationRoute
  '/curator/publishing': typeof CuratorPublishingRoute
  '/curator/quality': typeof CuratorQualityRoute
  '/curator/releases': typeof CuratorReleasesRoute
  '/curator/roadmap': typeof CuratorRoadmapRoute
  '/curator/settings': typeof CuratorSettingsRoute
  '/curator/sources': typeof CuratorSourcesRoute
  '/curator/technical': typeof CuratorTechnicalRoute
  '/curator/translations': typeof CuratorTranslationsRoute
  '/era/$eraId': typeof EraEraIdRoute
  '/figures/$figureId': typeof FiguresFigureIdRoute
  '/figures/quiz': typeof FiguresQuizRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/quiz/$eraId': typeof QuizEraIdRoute
  '/region/$regionId': typeof RegionRegionIdRoute
  '/theater/$matchId': typeof TheaterMatchIdRoute
  '/curator/': typeof CuratorIndexRoute
  '/figures/': typeof FiguresIndexRoute
  '/figures/collection/$collectionId': typeof FiguresCollectionCollectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/curator'
    | '/atlas'
    | '/chronicle'
    | '/cinema'
    | '/clubs'
    | '/compare'
    | '/cuisine'
    | '/culture'
    | '/football'
    | '/ideas'
    | '/lessons'
    | '/map'
    | '/moments'
    | '/passport'
    | '/profile'
    | '/showcase'
    | '/stargazing'
    | '/timeline'
    | '/words'
    | '/api/curator'
    | '/clubs/$clubId'
    | '/culture/$topicId'
    | '/curator/acquisitions'
    | '/curator/analytics'
    | '/curator/blueprint'
    | '/curator/content'
    | '/curator/contributors'
    | '/curator/coverage'
    | '/curator/decisions'
    | '/curator/education'
    | '/curator/football'
    | '/curator/media'
    | '/curator/preservation'
    | '/curator/publishing'
    | '/curator/quality'
    | '/curator/releases'
    | '/curator/roadmap'
    | '/curator/settings'
    | '/curator/sources'
    | '/curator/technical'
    | '/curator/translations'
    | '/era/$eraId'
    | '/figures/$figureId'
    | '/figures/quiz'
    | '/journeys/$journeyId'
    | '/quiz/$eraId'
    | '/region/$regionId'
    | '/theater/$matchId'
    | '/curator/'
    | '/figures/'
    | '/figures/collection/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/chronicle'
    | '/cinema'
    | '/clubs'
    | '/compare'
    | '/cuisine'
    | '/culture'
    | '/football'
    | '/ideas'
    | '/lessons'
    | '/map'
    | '/moments'
    | '/passport'
    | '/profile'
    | '/showcase'
    | '/stargazing'
    | '/timeline'
    | '/words'
    | '/api/curator'
    | '/clubs/$clubId'
    | '/culture/$topicId'
    | '/curator/acquisitions'
    | '/curator/analytics'
    | '/curator/blueprint'
    | '/curator/content'
    | '/curator/contributors'
    | '/curator/coverage'
    | '/curator/decisions'
    | '/curator/education'
    | '/curator/football'
    | '/curator/media'
    | '/curator/preservation'
    | '/curator/publishing'
    | '/curator/quality'
    | '/curator/releases'
    | '/curator/roadmap'
    | '/curator/settings'
    | '/curator/sources'
    | '/curator/technical'
    | '/curator/translations'
    | '/era/$eraId'
    | '/figures/$figureId'
    | '/figures/quiz'
    | '/journeys/$journeyId'
    | '/quiz/$eraId'
    | '/region/$regionId'
    | '/theater/$matchId'
    | '/curator'
    | '/figures'
    | '/figures/collection/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/curator'
    | '/atlas'
    | '/chronicle'
    | '/cinema'
    | '/clubs'
    | '/compare'
    | '/cuisine'
    | '/culture'
    | '/football'
    | '/ideas'
    | '/lessons'
    | '/map'
    | '/moments'
    | '/passport'
    | '/profile'
    | '/showcase'
    | '/stargazing'
    | '/timeline'
    | '/words'
    | '/api/curator'
    | '/clubs/$clubId'
    | '/culture/$topicId'
    | '/curator/acquisitions'
    | '/curator/analytics'
    | '/curator/blueprint'
    | '/curator/content'
    | '/curator/contributors'
    | '/curator/coverage'
    | '/curator/decisions'
    | '/curator/education'
    | '/curator/football'
    | '/curator/media'
    | '/curator/preservation'
    | '/curator/publishing'
    | '/curator/quality'
    | '/curator/releases'
    | '/curator/roadmap'
    | '/curator/settings'
    | '/curator/sources'
    | '/curator/technical'
    | '/curator/translations'
    | '/era/$eraId'
    | '/figures/$figureId'
    | '/figures/quiz'
    | '/journeys/$journeyId'
    | '/quiz/$eraId'
    | '/region/$regionId'
    | '/theater/$matchId'
    | '/curator/'
    | '/figures/'
    | '/figures/collection/$collectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuratorRouteRoute: typeof CuratorRouteRouteWithChildren
  AtlasRoute: typeof AtlasRoute
  ChronicleRoute: typeof ChronicleRoute
  CinemaRoute: typeof CinemaRoute
  ClubsRoute: typeof ClubsRouteWithChildren
  CompareRoute: typeof CompareRoute
  CuisineRoute: typeof CuisineRoute
  CultureRoute: typeof CultureRouteWithChildren
  FootballRoute: typeof FootballRoute
  IdeasRoute: typeof IdeasRoute
  LessonsRoute: typeof LessonsRoute
  MapRoute: typeof MapRoute
  MomentsRoute: typeof MomentsRoute
  PassportRoute: typeof PassportRoute
  ProfileRoute: typeof ProfileRoute
  ShowcaseRoute: typeof ShowcaseRoute
  StargazingRoute: typeof StargazingRoute
  TimelineRoute: typeof TimelineRoute
  WordsRoute: typeof WordsRoute
  ApiCuratorRoute: typeof ApiCuratorRoute
  EraEraIdRoute: typeof EraEraIdRoute
  FiguresFigureIdRoute: typeof FiguresFigureIdRoute
  FiguresQuizRoute: typeof FiguresQuizRoute
  JourneysJourneyIdRoute: typeof JourneysJourneyIdRoute
  QuizEraIdRoute: typeof QuizEraIdRoute
  RegionRegionIdRoute: typeof RegionRegionIdRoute
  TheaterMatchIdRoute: typeof TheaterMatchIdRoute
  FiguresIndexRoute: typeof FiguresIndexRoute
  FiguresCollectionCollectionIdRoute: typeof FiguresCollectionCollectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stargazing': {
      id: '/stargazing'
      path: '/stargazing'
      fullPath: '/stargazing'
      preLoaderRoute: typeof StargazingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football': {
      id: '/football'
      path: '/football'
      fullPath: '/football'
      preLoaderRoute: typeof FootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine': {
      id: '/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof CuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema': {
      id: '/cinema'
      path: '/cinema'
      fullPath: '/cinema'
      preLoaderRoute: typeof CinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator': {
      id: '/curator'
      path: '/curator'
      fullPath: '/curator'
      preLoaderRoute: typeof CuratorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/': {
      id: '/figures/'
      path: '/figures'
      fullPath: '/figures/'
      preLoaderRoute: typeof FiguresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator/': {
      id: '/curator/'
      path: '/'
      fullPath: '/curator/'
      preLoaderRoute: typeof CuratorIndexRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/theater/$matchId': {
      id: '/theater/$matchId'
      path: '/theater/$matchId'
      fullPath: '/theater/$matchId'
      preLoaderRoute: typeof TheaterMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$regionId': {
      id: '/region/$regionId'
      path: '/region/$regionId'
      fullPath: '/region/$regionId'
      preLoaderRoute: typeof RegionRegionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$eraId': {
      id: '/quiz/$eraId'
      path: '/quiz/$eraId'
      fullPath: '/quiz/$eraId'
      preLoaderRoute: typeof QuizEraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$journeyId': {
      id: '/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof JourneysJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/quiz': {
      id: '/figures/quiz'
      path: '/figures/quiz'
      fullPath: '/figures/quiz'
      preLoaderRoute: typeof FiguresQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/$figureId': {
      id: '/figures/$figureId'
      path: '/figures/$figureId'
      fullPath: '/figures/$figureId'
      preLoaderRoute: typeof FiguresFigureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/era/$eraId': {
      id: '/era/$eraId'
      path: '/era/$eraId'
      fullPath: '/era/$eraId'
      preLoaderRoute: typeof EraEraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator/translations': {
      id: '/curator/translations'
      path: '/translations'
      fullPath: '/curator/translations'
      preLoaderRoute: typeof CuratorTranslationsRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/technical': {
      id: '/curator/technical'
      path: '/technical'
      fullPath: '/curator/technical'
      preLoaderRoute: typeof CuratorTechnicalRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/sources': {
      id: '/curator/sources'
      path: '/sources'
      fullPath: '/curator/sources'
      preLoaderRoute: typeof CuratorSourcesRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/settings': {
      id: '/curator/settings'
      path: '/settings'
      fullPath: '/curator/settings'
      preLoaderRoute: typeof CuratorSettingsRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/roadmap': {
      id: '/curator/roadmap'
      path: '/roadmap'
      fullPath: '/curator/roadmap'
      preLoaderRoute: typeof CuratorRoadmapRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/releases': {
      id: '/curator/releases'
      path: '/releases'
      fullPath: '/curator/releases'
      preLoaderRoute: typeof CuratorReleasesRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/quality': {
      id: '/curator/quality'
      path: '/quality'
      fullPath: '/curator/quality'
      preLoaderRoute: typeof CuratorQualityRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/publishing': {
      id: '/curator/publishing'
      path: '/publishing'
      fullPath: '/curator/publishing'
      preLoaderRoute: typeof CuratorPublishingRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/preservation': {
      id: '/curator/preservation'
      path: '/preservation'
      fullPath: '/curator/preservation'
      preLoaderRoute: typeof CuratorPreservationRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/media': {
      id: '/curator/media'
      path: '/media'
      fullPath: '/curator/media'
      preLoaderRoute: typeof CuratorMediaRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/football': {
      id: '/curator/football'
      path: '/football'
      fullPath: '/curator/football'
      preLoaderRoute: typeof CuratorFootballRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/education': {
      id: '/curator/education'
      path: '/education'
      fullPath: '/curator/education'
      preLoaderRoute: typeof CuratorEducationRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/decisions': {
      id: '/curator/decisions'
      path: '/decisions'
      fullPath: '/curator/decisions'
      preLoaderRoute: typeof CuratorDecisionsRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/coverage': {
      id: '/curator/coverage'
      path: '/coverage'
      fullPath: '/curator/coverage'
      preLoaderRoute: typeof CuratorCoverageRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/contributors': {
      id: '/curator/contributors'
      path: '/contributors'
      fullPath: '/curator/contributors'
      preLoaderRoute: typeof CuratorContributorsRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/content': {
      id: '/curator/content'
      path: '/content'
      fullPath: '/curator/content'
      preLoaderRoute: typeof CuratorContentRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/blueprint': {
      id: '/curator/blueprint'
      path: '/blueprint'
      fullPath: '/curator/blueprint'
      preLoaderRoute: typeof CuratorBlueprintRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/analytics': {
      id: '/curator/analytics'
      path: '/analytics'
      fullPath: '/curator/analytics'
      preLoaderRoute: typeof CuratorAnalyticsRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/curator/acquisitions': {
      id: '/curator/acquisitions'
      path: '/acquisitions'
      fullPath: '/curator/acquisitions'
      preLoaderRoute: typeof CuratorAcquisitionsRouteImport
      parentRoute: typeof CuratorRouteRoute
    }
    '/culture/$topicId': {
      id: '/culture/$topicId'
      path: '/$topicId'
      fullPath: '/culture/$topicId'
      preLoaderRoute: typeof CultureTopicIdRouteImport
      parentRoute: typeof CultureRoute
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/api/curator': {
      id: '/api/curator'
      path: '/api/curator'
      fullPath: '/api/curator'
      preLoaderRoute: typeof ApiCuratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/collection/$collectionId': {
      id: '/figures/collection/$collectionId'
      path: '/figures/collection/$collectionId'
      fullPath: '/figures/collection/$collectionId'
      preLoaderRoute: typeof FiguresCollectionCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CuratorRouteRouteChildren {
  CuratorAcquisitionsRoute: typeof CuratorAcquisitionsRoute
  CuratorAnalyticsRoute: typeof CuratorAnalyticsRoute
  CuratorBlueprintRoute: typeof CuratorBlueprintRoute
  CuratorContentRoute: typeof CuratorContentRoute
  CuratorContributorsRoute: typeof CuratorContributorsRoute
  CuratorCoverageRoute: typeof CuratorCoverageRoute
  CuratorDecisionsRoute: typeof CuratorDecisionsRoute
  CuratorEducationRoute: typeof CuratorEducationRoute
  CuratorFootballRoute: typeof CuratorFootballRoute
  CuratorMediaRoute: typeof CuratorMediaRoute
  CuratorPreservationRoute: typeof CuratorPreservationRoute
  CuratorPublishingRoute: typeof CuratorPublishingRoute
  CuratorQualityRoute: typeof CuratorQualityRoute
  CuratorReleasesRoute: typeof CuratorReleasesRoute
  CuratorRoadmapRoute: typeof CuratorRoadmapRoute
  CuratorSettingsRoute: typeof CuratorSettingsRoute
  CuratorSourcesRoute: typeof CuratorSourcesRoute
  CuratorTechnicalRoute: typeof CuratorTechnicalRoute
  CuratorTranslationsRoute: typeof CuratorTranslationsRoute
  CuratorIndexRoute: typeof CuratorIndexRoute
}

const CuratorRouteRouteChildren: CuratorRouteRouteChildren = {
  CuratorAcquisitionsRoute: CuratorAcquisitionsRoute,
  CuratorAnalyticsRoute: CuratorAnalyticsRoute,
  CuratorBlueprintRoute: CuratorBlueprintRoute,
  CuratorContentRoute: CuratorContentRoute,
  CuratorContributorsRoute: CuratorContributorsRoute,
  CuratorCoverageRoute: CuratorCoverageRoute,
  CuratorDecisionsRoute: CuratorDecisionsRoute,
  CuratorEducationRoute: CuratorEducationRoute,
  CuratorFootballRoute: CuratorFootballRoute,
  CuratorMediaRoute: CuratorMediaRoute,
  CuratorPreservationRoute: CuratorPreservationRoute,
  CuratorPublishingRoute: CuratorPublishingRoute,
  CuratorQualityRoute: CuratorQualityRoute,
  CuratorReleasesRoute: CuratorReleasesRoute,
  CuratorRoadmapRoute: CuratorRoadmapRoute,
  CuratorSettingsRoute: CuratorSettingsRoute,
  CuratorSourcesRoute: CuratorSourcesRoute,
  CuratorTechnicalRoute: CuratorTechnicalRoute,
  CuratorTranslationsRoute: CuratorTranslationsRoute,
  CuratorIndexRoute: CuratorIndexRoute,
}

const CuratorRouteRouteWithChildren = CuratorRouteRoute._addFileChildren(
  CuratorRouteRouteChildren,
)

interface ClubsRouteChildren {
  ClubsClubIdRoute: typeof ClubsClubIdRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsClubIdRoute: ClubsClubIdRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

interface CultureRouteChildren {
  CultureTopicIdRoute: typeof CultureTopicIdRoute
}

const CultureRouteChildren: CultureRouteChildren = {
  CultureTopicIdRoute: CultureTopicIdRoute,
}

const CultureRouteWithChildren =
  CultureRoute._addFileChildren(CultureRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuratorRouteRoute: CuratorRouteRouteWithChildren,
  AtlasRoute: AtlasRoute,
  ChronicleRoute: ChronicleRoute,
  CinemaRoute: CinemaRoute,
  ClubsRoute: ClubsRouteWithChildren,
  CompareRoute: CompareRoute,
  CuisineRoute: CuisineRoute,
  CultureRoute: CultureRouteWithChildren,
  FootballRoute: FootballRoute,
  IdeasRoute: IdeasRoute,
  LessonsRoute: LessonsRoute,
  MapRoute: MapRoute,
  MomentsRoute: MomentsRoute,
  PassportRoute: PassportRoute,
  ProfileRoute: ProfileRoute,
  ShowcaseRoute: ShowcaseRoute,
  StargazingRoute: StargazingRoute,
  TimelineRoute: TimelineRoute,
  WordsRoute: WordsRoute,
  ApiCuratorRoute: ApiCuratorRoute,
  EraEraIdRoute: EraEraIdRoute,
  FiguresFigureIdRoute: FiguresFigureIdRoute,
  FiguresQuizRoute: FiguresQuizRoute,
  JourneysJourneyIdRoute: JourneysJourneyIdRoute,
  QuizEraIdRoute: QuizEraIdRoute,
  RegionRegionIdRoute: RegionRegionIdRoute,
  TheaterMatchIdRoute: TheaterMatchIdRoute,
  FiguresIndexRoute: FiguresIndexRoute,
  FiguresCollectionCollectionIdRoute: FiguresCollectionCollectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
