/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordsRouteImport } from './routes/words'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StargazingRouteImport } from './routes/stargazing'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as MapRouteImport } from './routes/map'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as CuisineRouteImport } from './routes/cuisine'
import { Route as CinemaRouteImport } from './routes/cinema'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FiguresIndexRouteImport } from './routes/figures.index'
import { Route as QuizEraIdRouteImport } from './routes/quiz.$eraId'
import { Route as FiguresQuizRouteImport } from './routes/figures.quiz'
import { Route as FiguresFigureIdRouteImport } from './routes/figures.$figureId'
import { Route as EraEraIdRouteImport } from './routes/era.$eraId'
import { Route as FiguresCollectionCollectionIdRouteImport } from './routes/figures.collection.$collectionId'

const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StargazingRoute = StargazingRouteImport.update({
  id: '/stargazing',
  path: '/stargazing',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineRoute = CuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaRoute = CinemaRouteImport.update({
  id: '/cinema',
  path: '/cinema',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresIndexRoute = FiguresIndexRouteImport.update({
  id: '/figures/',
  path: '/figures/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizEraIdRoute = QuizEraIdRouteImport.update({
  id: '/quiz/$eraId',
  path: '/quiz/$eraId',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresQuizRoute = FiguresQuizRouteImport.update({
  id: '/figures/quiz',
  path: '/figures/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresFigureIdRoute = FiguresFigureIdRouteImport.update({
  id: '/figures/$figureId',
  path: '/figures/$figureId',
  getParentRoute: () => rootRouteImport,
} as any)
const EraEraIdRoute = EraEraIdRouteImport.update({
  id: '/era/$eraId',
  path: '/era/$eraId',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresCollectionCollectionIdRoute =
  FiguresCollectionCollectionIdRouteImport.update({
    id: '/figures/collection/$collectionId',
    path: '/figures/collection/$collectionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/cinema': typeof CinemaRoute
  '/cuisine': typeof CuisineRoute
  '/culture': typeof CultureRoute
  '/ideas': typeof IdeasRoute
  '/lessons': typeof LessonsRoute
  '/map': typeof MapRoute
  '/moments': typeof MomentsRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/stargazing': typeof StargazingRoute
  '/timeline': typeof TimelineRoute
  '/words': typeof WordsRoute
  '/era/$eraId': typeof EraEraIdRoute
  '/figures/$figureId': typeof FiguresFigureIdRoute
  '/figures/quiz': typeof FiguresQuizRoute
  '/quiz/$eraId': typeof QuizEraIdRoute
  '/figures/': typeof FiguresIndexRoute
  '/figures/collection/$collectionId': typeof FiguresCollectionCollectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/cinema': typeof CinemaRoute
  '/cuisine': typeof CuisineRoute
  '/culture': typeof CultureRoute
  '/ideas': typeof IdeasRoute
  '/lessons': typeof LessonsRoute
  '/map': typeof MapRoute
  '/moments': typeof MomentsRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/stargazing': typeof StargazingRoute
  '/timeline': typeof TimelineRoute
  '/words': typeof WordsRoute
  '/era/$eraId': typeof EraEraIdRoute
  '/figures/$figureId': typeof FiguresFigureIdRoute
  '/figures/quiz': typeof FiguresQuizRoute
  '/quiz/$eraId': typeof QuizEraIdRoute
  '/figures': typeof FiguresIndexRoute
  '/figures/collection/$collectionId': typeof FiguresCollectionCollectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/cinema': typeof CinemaRoute
  '/cuisine': typeof CuisineRoute
  '/culture': typeof CultureRoute
  '/ideas': typeof IdeasRoute
  '/lessons': typeof LessonsRoute
  '/map': typeof MapRoute
  '/moments': typeof MomentsRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/stargazing': typeof StargazingRoute
  '/timeline': typeof TimelineRoute
  '/words': typeof WordsRoute
  '/era/$eraId': typeof EraEraIdRoute
  '/figures/$figureId': typeof FiguresFigureIdRoute
  '/figures/quiz': typeof FiguresQuizRoute
  '/quiz/$eraId': typeof QuizEraIdRoute
  '/figures/': typeof FiguresIndexRoute
  '/figures/collection/$collectionId': typeof FiguresCollectionCollectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/cinema'
    | '/cuisine'
    | '/culture'
    | '/ideas'
    | '/lessons'
    | '/map'
    | '/moments'
    | '/profile'
    | '/showcase'
    | '/stargazing'
    | '/timeline'
    | '/words'
    | '/era/$eraId'
    | '/figures/$figureId'
    | '/figures/quiz'
    | '/quiz/$eraId'
    | '/figures/'
    | '/figures/collection/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/cinema'
    | '/cuisine'
    | '/culture'
    | '/ideas'
    | '/lessons'
    | '/map'
    | '/moments'
    | '/profile'
    | '/showcase'
    | '/stargazing'
    | '/timeline'
    | '/words'
    | '/era/$eraId'
    | '/figures/$figureId'
    | '/figures/quiz'
    | '/quiz/$eraId'
    | '/figures'
    | '/figures/collection/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/cinema'
    | '/cuisine'
    | '/culture'
    | '/ideas'
    | '/lessons'
    | '/map'
    | '/moments'
    | '/profile'
    | '/showcase'
    | '/stargazing'
    | '/timeline'
    | '/words'
    | '/era/$eraId'
    | '/figures/$figureId'
    | '/figures/quiz'
    | '/quiz/$eraId'
    | '/figures/'
    | '/figures/collection/$collectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  CinemaRoute: typeof CinemaRoute
  CuisineRoute: typeof CuisineRoute
  CultureRoute: typeof CultureRoute
  IdeasRoute: typeof IdeasRoute
  LessonsRoute: typeof LessonsRoute
  MapRoute: typeof MapRoute
  MomentsRoute: typeof MomentsRoute
  ProfileRoute: typeof ProfileRoute
  ShowcaseRoute: typeof ShowcaseRoute
  StargazingRoute: typeof StargazingRoute
  TimelineRoute: typeof TimelineRoute
  WordsRoute: typeof WordsRoute
  EraEraIdRoute: typeof EraEraIdRoute
  FiguresFigureIdRoute: typeof FiguresFigureIdRoute
  FiguresQuizRoute: typeof FiguresQuizRoute
  QuizEraIdRoute: typeof QuizEraIdRoute
  FiguresIndexRoute: typeof FiguresIndexRoute
  FiguresCollectionCollectionIdRoute: typeof FiguresCollectionCollectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stargazing': {
      id: '/stargazing'
      path: '/stargazing'
      fullPath: '/stargazing'
      preLoaderRoute: typeof StargazingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine': {
      id: '/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof CuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema': {
      id: '/cinema'
      path: '/cinema'
      fullPath: '/cinema'
      preLoaderRoute: typeof CinemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/': {
      id: '/figures/'
      path: '/figures'
      fullPath: '/figures/'
      preLoaderRoute: typeof FiguresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$eraId': {
      id: '/quiz/$eraId'
      path: '/quiz/$eraId'
      fullPath: '/quiz/$eraId'
      preLoaderRoute: typeof QuizEraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/quiz': {
      id: '/figures/quiz'
      path: '/figures/quiz'
      fullPath: '/figures/quiz'
      preLoaderRoute: typeof FiguresQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/$figureId': {
      id: '/figures/$figureId'
      path: '/figures/$figureId'
      fullPath: '/figures/$figureId'
      preLoaderRoute: typeof FiguresFigureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/era/$eraId': {
      id: '/era/$eraId'
      path: '/era/$eraId'
      fullPath: '/era/$eraId'
      preLoaderRoute: typeof EraEraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures/collection/$collectionId': {
      id: '/figures/collection/$collectionId'
      path: '/figures/collection/$collectionId'
      fullPath: '/figures/collection/$collectionId'
      preLoaderRoute: typeof FiguresCollectionCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  CinemaRoute: CinemaRoute,
  CuisineRoute: CuisineRoute,
  CultureRoute: CultureRoute,
  IdeasRoute: IdeasRoute,
  LessonsRoute: LessonsRoute,
  MapRoute: MapRoute,
  MomentsRoute: MomentsRoute,
  ProfileRoute: ProfileRoute,
  ShowcaseRoute: ShowcaseRoute,
  StargazingRoute: StargazingRoute,
  TimelineRoute: TimelineRoute,
  WordsRoute: WordsRoute,
  EraEraIdRoute: EraEraIdRoute,
  FiguresFigureIdRoute: FiguresFigureIdRoute,
  FiguresQuizRoute: FiguresQuizRoute,
  QuizEraIdRoute: QuizEraIdRoute,
  FiguresIndexRoute: FiguresIndexRoute,
  FiguresCollectionCollectionIdRoute: FiguresCollectionCollectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
